[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "odoo-mcp-server"
version = "0.1.0"
description = "MCP Server for Odoo Integration"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
]
keywords = ["odoo", "mcp", "server"]
authors = [
    {name = "Biszx", email = "isares.br@gmail.com"}
]
dependencies = [
    "loguru>=0.7.3",
    "mcp[cli]>=1.9.4",
    "odoorpc>=0.10.1",
    "python-dotenv>=1.1.1",
]

[project.urls]
Homepage = "https://github.com/isares-br/odoo-mcp-server"
Issues = "https://github.com/isares-br/odoo-mcp-server/issues"

[project.scripts]
odoo-mcp = "odoo_mcp_server.__main__:main"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["odoo_mcp_server"]

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "pre-commit>=4.2.0",
    "pylint>=3.3.7",
    "ruff>=0.12.0",
]
