name: Publish to PyPI

on:
  release:
    types: [published]
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      # - name: Build
      #   run: uv build
      # - name: Publish
      #   run: uv publish -t ${{ secrets.PYPI_API_TOKEN }}
